name             'ceph'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ceph'
long_description 'Installs/Configures ceph'
version          '0.1.0'
